version: "3.8"
services:
  api:
    build:
      context: .
      target: "$COMPOSE_TARGET"
    environment: 
      - B_REDIS_HOST=redis
      - B_REDIS_PORT=6379
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on: 
      - redis
  redis:
    image: "redis:alpine"
